class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @ads = Advertisement.new
    @ads.title = params[:advertisement][:title]
    @ads.body = params[:advertisement][:body]
    @ads.price = params[:advertisement][:price]
    
    if @ads.save
      #display a success message using flash[:notice]
      flash[:notice] = "Your Ads was successfully created"
      #redirect the user to the route generated by @post
      redirect_to @ads
    else
      flash.now[:alert] = "There was an error while create the Ads. Please try again."
      render :new
    end
  end
end
