class PostsController < ApplicationController
  def index
    @posts = Post.all
    #screening sensitive post
    #@posts.each_with_index {|p,i| p.title = "SPAM" if i==0 || (i+1)%5==0 }
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    
    if @post.save
      #display a success message using flash[:notice]
      flash[:notice] = "Post was saved"
      #redirect the user to the route generated by @post
      redirect_to @post
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
    
  end
  
  def edit
  end
end
